//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.08 at 05:08:21 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://kirillkotov.com/soapspringbootlect/dto", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kirillkotov.soapspringbootlect.dto;
