//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.20 at 01:06:09 PM AZT 
//


package com.kirillkotov.soapspringbootlect.example.dto;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kirillkotov.soapspringbootlect.example.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kirillkotov.soapspringbootlect.example.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCountriesResponse }
     * 
     */
    public GetCountriesResponse createGetCountriesResponse() {
        return new GetCountriesResponse();
    }

    /**
     * Create an instance of {@link GetCountryNameRequest }
     * 
     */
    public GetCountryNameRequest createGetCountryNameRequest() {
        return new GetCountryNameRequest();
    }

    /**
     * Create an instance of {@link GetCountryPopulationRequest }
     * 
     */
    public GetCountryPopulationRequest createGetCountryPopulationRequest() {
        return new GetCountryPopulationRequest();
    }

    /**
     * Create an instance of {@link GetCountryResponse }
     * 
     */
    public GetCountryResponse createGetCountryResponse() {
        return new GetCountryResponse();
    }

    /**
     * Create an instance of {@link PostCountryRequest }
     * 
     */
    public PostCountryRequest createPostCountryRequest() {
        return new PostCountryRequest();
    }

}
