//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.27 at 12:53:07 PM AZT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://kirillkotov.com/soapspringbootlect/example/dto", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kirillkotov.soapspringbootlect.example.dto;
